spring:
  main:
    banner-mode: off

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot
      username: root
      password: 2514632453
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
    banner: off
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl